#!/bin/sh

make clean; perl Makefile.PL; make dist
cd other/drv-linux; make clean; perl Makefile.PL; make dist; cd ../..
cd other/drv-parport; make clean; perl Makefile.PL; make dist; cd ../..
cd other/jaycar; make clean; perl Makefile.PL; make dist; cd ../..

