
all: teston testoff teston1 teston2 teston3 teston13 teston123 testbyte

clean: 
	rm teston testoff teston1 teston2 teston3 teston13 teston123 testbyte

teston3: teston3.c
	gcc -O2 -o teston3 teston3.c

teston13: teston13.c
	gcc -O2 -o teston13 teston13.c

teston123: teston123.c
	gcc -O2 -o teston123 teston123.c

teston2: teston2.c
	gcc -O2 -o teston2 teston2.c

teston1: teston1.c
	gcc -O2 -o teston1 teston1.c

teston: teston.c
	gcc -O2 -o teston teston.c

testoff: testoff.c
	gcc -O2 -o testoff testoff.c

testbyte: testbyte.c
	gcc -O2 -o testbyte testbyte.c

setbyte: setbyte.c
	gcc -O2 -o setbyte setbyte.c
